name: fln_mangadex_api
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ^3.6.0-149.3.beta

dependencies:
  chopper: ^8.0.3
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  uuid: ^4.5.0

dev_dependencies:
  lints: ^5.1.0
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  chopper_generator: ^8.0.3
