name: fln_mangadex_api
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ^3.6.0-149.3.beta

dependencies:
  collection: ^1.19.0
  dio: ^5.7.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  retrofit: ^4.4.1
  uuid: ^4.5.0

dev_dependencies:
  build_runner: ^2.4.12
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  lints: ^4.0.0
  retrofit_generator: ^9.1.2
